---

services:
  proxy:
    image: tecnativa/docker-socket-proxy
    restart: unless-stopped
    ports:
      - 2375:2375
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:z
    networks:
      - proxy
    environment
      - BUILD=1
      - COMMIT=1
      - CONFIGS=1:
      - CONTAINERS=1
      - DISTRIBUTION=1
      - EXEC=1
      - GRPC=1
      - IMAGES=1
      - INFO=1
      - NETWORKS=1
      - NODES=1
      - PLUGINS=1
      - SERVICES=1
      - SESSION=1
      - SWARM=1
      - SYSTEM=1
      - TASKS=1
      - VOLUMES=1
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.services.dockerproxy-service.loadbalancer.server.port=2375"
      # HTTPS configuration
      - "traefik.http.routers.dockerproxy-https.rule=Host(`${PROXY_HOST}`)"
      - "traefik.http.routers.dockerproxy-https.entrypoints=docker-proxy"
      - "traefik.http.routers.dockerproxy-https.tls=true"
      - "traefik.http.routers.dockerproxy-https.tls.certresolver=tailresolver"
      - "traefik.http.routers.dockerproxy-https.service=dockerproxy-service"

networks:
  proxy:
    external: true
