---

services:
  proxy:
    image: tecnativa/docker-socket-proxy
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:roz
    networks:
      - proxy
    environment:
      CONTAINERS: 1
      IMAGES: 1
      NETWORKS: 1
      SERVICES: 1
      TASKS: 1
      VOLUMES: 1
    labels:
      - "traefik.enable=true"
      # HTTPS configuration
      - "traefik.http.routers.dockerproxy-https.rule=Host(`${PROXY_HOST}`)"
      - "traefik.http.routers.dockerproxy-https.entrypoints=docker-proxy"
      - "traefik.http.routers.dockerproxy-https.tls=true"
      - "traefik.http.routers.dockerproxy-https.tls.certresolver=tailresolver"
      - "traefik.http.routers.dockerproxy-https.service=dockerproxy-service"
      - "traefik.http.services.dockerproxy-service.loadbalancer.server.port=2375"
      # HTTP to HTTPS redirection
      - "traefik.http.routers.dockerproxy-http.rule=Host(`${PROXY_HOST}`)"
      - "traefik.http.routers.dockerproxy-http.entrypoints=http"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.dockerproxy-http.middlewares=redirect-to-https"

networks:
  proxy:
    external: true
