---

services:
  proxy:
    image: lscr.io/linuxserver/socket-proxy:latest
    container_name: socket-proxy
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:roz
    networks:
      - default
      - proxy
    environment:
      - BUILD=1
      - COMMIT=1
      - CONFIGS=1
      - CONTAINERS=1
      - DISTRIBUTION=1
      - EXEC=1
      - GRPC=1
      - IMAGES=1
      - INFO=1
      - NETWORKS=1
      - NODES=1
      - PLUGINS=1
      - SERVICES=1
      - SESSION=1
      - SYSTEM=1
      - TASKS=1
      - VOLUMES=1
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.services.dockerproxy-service.loadbalancer.server.port=2375"
      # HTTPS configuration
      - "traefik.http.routers.dockerproxy-https.rule=Host(`${PROXY_HOST}`)"
      - "traefik.http.routers.dockerproxy-https.entrypoints=docker-proxy"
      - "traefik.http.routers.dockerproxy-https.tls=true"
      - "traefik.http.routers.dockerproxy-https.tls.certresolver=tailresolver"
      - "traefik.http.routers.dockerproxy-https.service=dockerproxy-service"
    read_only: true
    tmpfs:
      - /run

networks:
  proxy:
    external: true
