---

services:
  traefik:
    image: traefik:v3.0
    restart: always
    networks:
      - proxy
    ports:
      - 2375:2375
    command:
      - "--entrypoints.docker-proxy.address=:2375"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--certificatesresolvers.tailresolver.tailscale=true"
    volumes:
      - /var/run/tailscale/tailscaled.sock:/var/run/tailscale/tailscaled.sock:z
      - /var/run/docker.sock:/var/run/docker.sock:roz
      - letsencrypt:/letsencrypt:Z
    labels:
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true

volumes:
  letsencrypt:
