---

services:
  shlink:
    image: shlinkio/shlink:stable
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - DEFAULT_DOMAIN=${DEFAULT_DOMAIN}
      - IS_HTTPS_ENABLED=true
      - GEOLITE_LICENSE_KEY=${GEOLITE_LICENSE_KEY}
      - DB_DRIVER=maria
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=database
    depends_on:
      - database
    networks:
      - default
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${NAME}.rule=${RULE}"
      - "traefik.http.routers.${NAME}.entrypoints=websecure"
      - "traefik.http.routers.${NAME}.tls.certresolver=letsencrypt"
      - "traefik.http.services.${NAME}.loadbalancer.server.port=8080"
      - "traefik.docker.network=proxy"

  database:
    image: mariadb:10.8
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${DB_NAME}
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_PASSWORD}
    volumes:
      - /opt/shlink/db_data:/var/lib/mysql

networks:
  proxy:
    external: true