---

services:
  wings:
    image: ghcr.io/pterodactyl/wings:latest
    restart: always
    networks:
      - wings0
      - proxy
    ports:
      - "2022:2022"
    tty: true
    environment:
      TZ: ${TZ}
      WINGS_UID: ${UID}
      WINGS_GID: ${GID}
      WINGS_USERNAME: pterodactyl
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wings.rule=Host(`${PROXY_HOST}`)"
      - "traefik.http.routers.wings.entrypoints=wings"
      - "traefik.http.routers.wings.tls.certresolver=tailresolver"
      - "traefik.http.services.wings.loadbalancer.server.port=8080"
      - "traefik.docker.network=proxy"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:z"
      - "/var/lib/docker/containers/:/var/lib/docker/containers/:z"
      - "/etc/pterodactyl/:/etc/pterodactyl/:z"
      - "/var/lib/pterodactyl/:/var/lib/pterodactyl/:z"
      - "/var/log/pterodactyl/:/var/log/pterodactyl/:z"
      - "/tmp/pterodactyl/:/tmp/pterodactyl/:z"
      - "/etc/ssl/certs:/etc/ssl/certs:roz"

networks:
  proxy:
    external: true
  wings0:
    name: wings0
    driver: bridge
    ipam:
      config:
        - subnet: "172.21.0.0/16"
    driver_opts:
      com.docker.network.bridge.name: wings0