http:
  middlewares:
    kasm-custom-headers:
      headers:
        customResponseHeaders:
          Cross-Origin-Embedder-Policy: "require-corp"
          Cross-Origin-Opener-Policy: "same-origin"
          Cross-Origin-Resource-Policy: "same-site"

    kasm-trailing-slash:
      redirectRegex:
        regex: "^(.+[^/])$"
        replacement: "$${1}/"
        permanent: false