name: adguardhome

services:
  home:
    image: adguard/adguardhome
    restart: unless-stopped
    networks:
      default:
      cloudflare_default:
      macvlan_network:
        ipv4_address: ${IP}
    volumes:
      - config:/opt/adguardhome/conf:Z # app configuration
      - work:/opt/adguardhome/work:Z # app working directory

  sync:
    image: lscr.io/linuxserver/adguardhome-sync:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - CONFIGFILE=/config/adguardhome-sync.yaml
    volumes:
      - sync:/config:Z
    restart: unless-stopped
    depends_on:
      - home

networks:
  cloudflare_default:
    external: true
  macvlan_network:
    external: true

volumes:
  config:
    driver: local
  work:
    driver: local
  sync:
    driver: local
