http:
  routers:
    plex:
      rule: "Host(`play-alt.3pic.app`)"
      entryPoints:
        - websecure
      service: plex
      tls:
        certResolver: letsencrypt

  services:
    plex:
      loadBalancer:
        servers:
          - url: "https://192.168.1.10:32400"
        passHostHeader: true
        serversTransport: "insecure-transport"

  serversTransports:
    insecure-transport:
      insecureSkipVerify: true